import type { Article } from "@/content/types";

const article: Article = {
  "slug": "positive-vs-negative-gamma",
  "title": "Positive vs Negative Gamma: Why the Sign Matters",
  "dek": "Negative gamma means dealers chase and amplify swings. Positive gamma dampens. Thursday vs Friday QQQ shows both regimes on the Cos map.",
  "date": "2026-09-28",
  "section": "options",
  "kicker": "evergreen",
  "asOf": "Mon Sep 28, 2026, ~1:00 AM PT (overnight desk; worked examples Thu Sep 24 + Fri Sep 25 US cash)",
  "ogImage": "/og/positive-vs-negative-gamma.png",
  "ogAlt": "Positive vs negative gamma: dampen vs amplify. Thu Neg γ and Fri Pos γ QQQ class. @CosAnalyst. BOOK FACT · NOT A TICKET",
  "also": ["research", "equities", "markets"],
  "body": [
    {"type": "figure", "src": "/og/positive-vs-negative-gamma.png", "alt": "Positive vs negative gamma: dampen vs amplify. Thu Neg γ and Fri Pos γ QQQ class. @CosAnalyst. BOOK FACT · NOT A TICKET", "caption": "Same hedge engine. Opposite job. · BOOK FACT · NOT A TICKET"},
    {"type": "callout", "text": "As of Mon Sep 28, 2026, ~1:00 AM PT. Worked examples use Thu Sep 24 and Fri Sep 25 US cash. BOOK FACT · NOT A TICKET · SIMULATED RESEARCH"},
    {"type": "lede", "text": "**Negative gamma** means the estimated dealer book is short gamma, so hedges tend to chase price and amplify swings. Positive gamma is the opposite job: dealers fade extremes and dampen the tape. Neither sign is bullish or bearish. Both describe the character of the move, not where it has to finish."},
    {"type": "p", "text": "Thursday Nasdaq opened under a put wall in a Negative Gamma book and still closed higher."},
    {"type": "p", "text": "Friday the same index sat in Positive Gamma, closed under the call wall and above the flip, and the tape felt sticky instead of stretched."},
    {"type": "p", "text": "Same hedge engine. Opposite job."},
    {"type": "h2", "text": "What does negative gamma mean in options?"},
    {"type": "p", "text": "Dealers take the other side of a lot of listed options. They hedge in QQQ, SPY, or the futures. **Gamma** is how fast that hedge size changes when price ticks. When the estimated book is short gamma, a down-move can force more selling. An up-move can force more buying. The hedge chases. Swings can outrun the news."},
    {"type": "p", "text": "That is **negative gamma**: an amplifying regime. It is not a sell ticket. Thursday proved the point. Cos stamped Negative Gamma at 11:14 PT with net GEX about **-$331 million**, and QQQ still closed **741.10**, above the flip."},
    {"type": "p", "text": "Parent map: [What is gamma exposure?](https://cosanalyst.com/articles/what-is-gamma-exposure/)."},
    {"type": "figure", "src": "/og/positive-vs-negative-gamma-01.png", "alt": "Side-by-side: positive gamma dampens, negative gamma amplifies.", "caption": "One mechanism, two signs. Cos educational diagram."},
    {"type": "h2", "text": "What does positive and negative gamma mean?"},
    {"type": "p", "text": "Two signs. One mechanism."},
    {"type": "p", "text": "**Positive gamma** (dealers long γ): sell rips, buy dips. The hedge leans against the move. Realized swings often shrink. The tape can feel bored."},
    {"type": "p", "text": "**Negative gamma** (dealers short γ): chase. Sell into weakness, buy into strength. Ranges can feel too big for the headline."},
    {"type": "p", "text": "GEX maps are estimates from listed open interest and an assumption about who holds what. Dealers' true inventory is not public. Cos stamps a time and treats the print as a map."},
    {"type": "p", "text": "Three landmarks show up on every Cos sheet:"},
    {"type": "list", "items": ["**Put wall (P1):** heavy put-gamma strike. Below it in a short-gamma book, hedges can speed both directions.", "**Call wall (C1):** heavy call cluster. Rallies often slow there because the hedge sells into strength.", "**HVL / flip:** Cos's name for the estimated zero-crossing. Above it, dampening is more likely. Below it, amplification is more likely. Gamma flip and call-put wall explainers are next after the [parent hub](https://cosanalyst.com/articles/what-is-gamma-exposure/)."]},
    {"type": "h2", "text": "What is a positive gamma environment?"},
    {"type": "p", "text": "A **positive gamma environment** is when the estimated dealer book is long gamma near the current price. Hedges fade extremes. Moves still happen. They often look smaller than the story on the screen."},
    {"type": "p", "text": "Friday Sep 25 was the classroom next to Thursday's amplifier."},
    {"type": "p", "text": "QQQ cash: open **742.83**, high **745.92**, low **739.64**, close **744.5**."},
    {"type": "p", "text": "Cos map at 12:14 PT: call wall **745**, HVL **738**, put wall **736**. Net GEX about **+$591 million**. Profile: **Positive Gamma**. Cash closed **UNDER C1** and **ABOVE HVL**."},
    {"type": "p", "text": "SPY closed **771.35** (walls **772 / 767 / 764**, net about **+$866.2M**). VIX about **14.86-14.87**. Sticky-tape look: hedge more likely to lean against the move than chase it."},
    {"type": "figure", "src": "/og/positive-vs-negative-gamma-03.png", "alt": "Thu Negative Gamma vs Fri Positive Gamma QQQ contrast on Cos stamped maps.", "caption": "Same week, opposite gamma character."},
    {"type": "h2", "text": "What does a negative gamma day look like?"},
    {"type": "p", "text": "Thursday, September 24, 2026. QQQ: open **735.29**, high **742.66**, low **734.62**, close **741.10**."},
    {"type": "p", "text": "Cos map at 11:14 PT: put wall **736**, HVL flip **739**, call wall **742**. Midday profile: **Negative Gamma**. Net GEX about **-$331 million**."},
    {"type": "p", "text": "QQQ opened **under** 736 and printed **734.62**. In a short-gamma regime, a break under a put wall is where dealer hedges can push with the tape."},
    {"type": "p", "text": "The wall got reclaimed. Cash crossed **739**. The high **742.66** tagged toward C1 **742**. Close **741.10** sat above HVL **739** and under C1 **742**."},
    {"type": "figure", "src": "/og/positive-vs-negative-gamma-02.png", "alt": "$QQQ Thursday path under 736 put wall through 739 flip toward 742, close 741.10.", "caption": "Thursday's negative gamma walk. Map as of 11:14 PT."},
    {"type": "p", "text": "Negative gamma did not call a down day. It described the morning's extra slack, then the repair. SPY closed **767.18**. VIX about **15.67**."},
    {"type": "h2", "text": "Two regimes for the next session"},
    {"type": "p", "text": "**A. Positive-gamma hold above the flip.** Price stays above the stamped HVL while net GEX is estimated positive. Dealer hedges are more likely to **dampen**. Moves can still print. They often look smaller than the headline. Friday's close under C1 **745** and above HVL **738** is that corridor."},
    {"type": "p", "text": "**B. Negative-gamma break under the put wall.** Price loses P1 while the book is still estimated short gamma. Dealers chasing can make the range feel too big for the news. Thursday's open under **736** was that setup. The reclaim later showed the map can repair inside the same session."},
    {"type": "p", "text": "Neither path is a buy or a sell."},
    {"type": "h2", "text": "Levels from the Cos book"},
    {"type": "p", "text": "**Thu Sep 24 map (11:14 PT), Negative Gamma class**"},
    {"type": "list", "items": ["**QQQ Above 742 (C1):** testing the call wall after the repair.", "**Between 739 and 742:** afternoon corridor. Flip held. Call wall not accepted on the close.", "**Below 736 (P1):** put wall lost again. In a still-negative book, swings can stretch."]},
    {"type": "p", "text": "**Fri Sep 25 map (12:14 PT), Positive Gamma contrast**"},
    {"type": "list", "items": ["**QQQ C1 745 / HVL 738 / P1 736.** Close **744.5** UNDER C1 / ABOVE HVL.", "**SPY** C1 **772** / HVL **767** / P1 **764**. Close **771.35**."]},
    {"type": "p", "text": "Interim until the next Cos stamp. Open interest rewrites the map."},
    {"type": "h2", "text": "What should you watch next?"},
    {"type": "list", "items": ["**Which sign is stamped at the open.** Positive vs negative gamma sets whether hedges are more likely to fade or chase.", "**The put wall and the flip.** Holding the HVL keeps a repaired read. Losing P1 in a still-negative book is when the amplifier tends to show up.", "**A new Cos stamp.** Thursday's 11:14 PT and Friday's 12:14 PT reads are not Monday's book.", "**FOMC on the calendar, not as a GEX forecast.** Next meetings: **October 27-28** and **December 8-9, 2026**. Event days can flip a gamma regime because new options print and implied vol jumps.", "**Overnight into Mon ~1 AM PT (Yahoo):** ES ~**7769.75**, NQ ~**30606**, VIX ~**16.2**. Soft fade, not a spike."]},
    {"type": "h2", "text": "FAQ"},
    {"type": "h3", "text": "What does negative gamma mean in options?"},
    {"type": "p", "text": "The estimated dealer book is short gamma, so hedges tend to chase price and amplify swings. It maps volatility character, not direction."},
    {"type": "h3", "text": "What does positive and negative gamma mean?"},
    {"type": "p", "text": "Positive: dealers fade extremes and dampen. Negative: dealers chase and amplify. Same hedge engine. Opposite job."},
    {"type": "h3", "text": "What is a positive gamma environment?"},
    {"type": "p", "text": "A session where estimated dealer gamma is positive near the current price. Hedges lean against the move. Friday Sep 25 QQQ (net about +$591M, close under C1 / above HVL) is the Cos classroom."},
    {"type": "h3", "text": "Is negative gamma bearish?"},
    {"type": "p", "text": "No. Thursday was Negative Gamma and QQQ still closed higher. The sign describes how hedges may behave if price gets there, not where the close must land."},
    {"type": "h2", "text": "The aha"},
    {"type": "p", "text": "People hear **negative gamma** and reach for a red candle. That is the wrong reflex."},
    {"type": "p", "text": "Negative gamma is an amplifier. Positive gamma is a dampener. Thursday opened under 736 in Negative Gamma and closed 741.10 above the flip. Friday sat in Positive Gamma and closed sticky under the call wall. The map did not fail either day. The people who asked it for direction did."},
    {"type": "p", "text": "Read the sign as a job description for the hedge. Fade or chase. Then the walls look like crowded strikes with a mechanical job."},
    {"type": "p", "text": "Full research archive: https://cosanalyst.com/articles/positive-vs-negative-gamma/"},
    {"type": "p", "text": "Parent hub: https://cosanalyst.com/articles/what-is-gamma-exposure/"},
    {"type": "p", "text": "BOOK FACT · NOT A TICKET"},
    {"type": "p", "text": "SIMULATED RESEARCH"},
    {"type": "p", "text": "Not financial advice. GEX is an estimate. Dealers' true inventory is not public. Levels are a map, not a ticket."},
  ]
};

export default article;
